### ISSUE TITLE
Add flag to `hit amend` not to perform push

### ISSUE THREAD

**Issue by chshersh** [kowainik/hit-on#107]
Sometimes I want to amend a commit but locally because later I may want to do `hit fresh` or `hit sync` or something else. It would be nice to have a flag for `hit amend` not to push. But  I have no idea how to call it. Any suggestions? :slightly_smiling_face:

**Comment by vrom911** [comment]
`-n`? We are using it for `commit` command to not add issue number.

**Comment by chshersh** [comment]
@vrom911 Good idea! I was also thinking about `[-l|--local]`

**Comment by Nimor111** [comment]
I'd like to take this if possible. :)
Anything I should look out for specifically?

**Comment by vrom911** [comment]
Thanks @Nimor111 :+1: 
Basically, the task is to patch this option:

https://github.com/kowainik/hit-on/blob/master/src/Hit/Cli.hs#L72

to have a boolean field which would turn-off the push for this command. (By default it still should be pushing). In `optparse-applicative` parser you should add the option `-l | --local` which would be responsible for that.
And, finally, `runAmend` function should be patched accordingly:

https://github.com/kowainik/hit-on/blob/master/src/Hit/Git.hs#L139-L143

Good luck with the first Haskell contribution! Hope we can be helpful in the review :slightly_smiling_face:

**Comment by Nimor111** [comment]
Thanks for the great pointers!
