### ISSUE TITLE
test git issue

### ISSUE THREAD

**Issue by bangn** [kowainik/hit-on#115]

**Comment by bangn** [comment]
Sorry my bad

**Comment by chshersh** [comment]
@bangn No worries! If you're working on testing `hit-on`, we've created a separate repository for this purpose to not mess with this one:

* https://github.com/kowainik/hit-off

Just let us know what you're working on, so we can discuss how this should be done :slightly_smiling_face:

**Comment by bangn** [comment]
Cool. Thanks @chshersh. I just commented on one of the hit-on issue :)
