### ISSUE TITLE
Make `hit status` more precise when files are renamed

### ISSUE THREAD

**Issue by chshersh** [kowainik/hit-on#122]
Sometimes the output of `hit status` is not precise enough when files are renamed. Here is the incorrect output:

```shell
$ hit status
 ➤  Current branch: chshersh/230-Add-AppVeyor-CI
modified  README.md                                  | 0 
modified  appveyor.yml                               | 5 +++--
renamed   examples/Playground.hs -> examples/Main.hs | 4 ++--
modified  tomland.cabal                              | 2 +-
```

Output of used `git` commands:

```shell
$ git diff HEAD --stat
 README.md                           | 5 +++--
 appveyor.yml                        | 4 ++--
 examples/{Playground.hs => Main.hs} | 0
 tomland.cabal                       | 2 +-
 4 files changed, 6 insertions(+), 5 deletions(-)

$ git diff HEAD --name-status
M       README.md
M       appveyor.yml
R100    examples/Playground.hs  examples/Main.hs
M       tomland.cabal
```

cc @crtschin (maybe you have some ideas since you've implemented renamed files support)

**Comment by crtschin** [comment]
It seems like a bug with the order the stats are printed in. Can I try fixing it?

**Comment by chshersh** [comment]
@crtschin Sure, you can try! Here is some background: I believe this is happening because of sorting:

https://github.com/kowainik/hit-on/blob/caae31f20ee692cbe765bf8f486521267f21ef90/src/Hit/Git/Status.hs#L149-L150

However, sorting is required because the output of these two commands is not guaranteed to produce entries in the same order. When I tested it on macOS, the position of hidden files was different in these two commands, hence the sorting.
