### ISSUE TITLE
Improve `stash` command

### ISSUE THREAD

**Issue by vrom911** [kowainik/hit-on#135]
- named stashing
 - list of stashes
 - show the diff of the particular stash
 - clear stashes

We can work on polishing this command. Let me know what do you think about what could be included :slightly_smiling_face:

**Comment by chshersh** [comment]
Ideally, I'd love to keep the current behavior: `hit stash` stashes and `hit unstash` unstashes. And those commands take an argument, then it's a named stash, like `hit stash doc-fix`. However, this means that we will need to implement separate commands, like `hit stash-list`, `hit stash-clear`. Alternatively, names can be passed as parameters and all commands will be nested. So two versions
In short:

**Version 1**

```
hit stash
hit stash temp-fix
hit unstash
hit unstash temp-fix
hit stash-list
hit stash-diff
```

**Version 2**

```
hit stash
hit stash --name temp-fix
hit stash list
hit stash diff [Possible arguments]
hit stash clear
```

What would be the most convenient interface, you think? Also, I'm not sure whether `optparse-applicative` allows implementing the second version.
