### ISSUE TITLE
Upgrade to github-0.26

### ISSUE THREAD

**Issue by vrom911** [kowainik/hit-on#139]
[Changelog](https://hackage.haskell.org/package/github-0.24/changelog)

**Comment by chshersh** [comment]
@vrom911 Now we can switch to `github-0.25` since it contains your fix for `IssueNumber` 🙂 

* http://hackage.haskell.org/package/github-0.25/changelog

**Comment by chshersh** [comment]
The API is changed to significantly. It's not going to happen.
