### ISSUE TITLE
[RFC] Show issues from the current milestone

### ISSUE THREAD

**Issue by vrom911** [kowainik/hit-on#157]

**Comment by chshersh** [comment]
Wow, I haven't thought about it! I see how this can be useful. I wonder how CLI could look like 🤔 Were you thinking about the `--milestone` flag for the `hit issue` command or a separate set of commands like `hit milestone [list|create|close...]`?

**Comment by vrom911** [comment]
I see how both of the options are possible and useful.
Also, the open question is how to distinguish the current milestone? By the date of creation, or the due date?
Need to think about it more 🤔

**Comment by chshersh** [comment]
I understand the dillemma and I agree that both  versions are useful.
Regarding the current milestone -- I guess it makes sense that the current one is the oldest one (in terms of creation date). At least this is true for our cases. But I also can imagine cases, when it's not true. Need to think indeed...
