### ISSUE TITLE
[RFC] wip commits

### ISSUE THREAD

**Issue by vrom911** [kowainik/hit-on#159]
- No issue numbers
- Pushed to origin

I need this very often, so I usually do:

```
hit commit -np "WIP"
```

Would it be useful to have this logic somewhere?
I only concerned about how to handle cases with `master`. I guess we need to somehow create a wip branch, but not sure...

**Comment by chshersh** [comment]
@vrom911 Interesting idea! I like having `hit wip` command, which does exactly what you described 👍 

I agree that the case with `master` is a bit tricky and worth thinking about 🤔 I see a few options:

* Create `<name>/wip` branch (as you proposed)
    + **Pros**: minimal effort, not extra flags required
    + **Cons:** need to rename later both locally and on GitHub (we currently don't have such a command in `hit`); can't have multiple different `wip` commits from `master`
* Ask the name/issue for the new branch interactively
    + **Pros**: better branch name immediately, more options for the user
    + **Cons:** slower, more flags/configuration/actions to do to create a `WIP` commit

**Comment by vrom911** [comment]
@chshersh , great summary!
For me personally the `master` use case is rarer, as I usually working on a particular issue and want to make a WIP commit. However, for sure the airbag should be in place. I would go for the first option, as I don't usually care about the collision between my `wip` branches. But the second one is totally legit. So need to think more about each one.
