### ISSUE TITLE
Describe the required oauth privilages needed

### ISSUE THREAD

**Issue by arbus** [kowainik/hit-on#47]
When generating the personal access token, we need to specify the scope needed for the token. This should be specified in the README

**Comment by ChShersh** [comment]
Currently we only fetch information about issues. It's not clear from the GitHub API which scopes are responsible for this...

**Comment by vrom911** [comment]
I have `repo` and `user` scopes, but probably it is more than needed. I will play around with it to determine the minimum needs.
