### ISSUE TITLE
parseOwnerRepo expects a .git suffix but that is optional

### ISSUE THREAD

**Issue by arbus** [kowainik/hit-on#50]

**Comment by vrom911** [comment]
@arbus Can you please give the link to the docs on that? And just provide the details on how do you get the link without `.git` suffix? The standard ways don't seem to have this behaviour.

**Comment by arbus** [comment]
When I close a new repo, I usually just type out the URL and have never included the `.git` and it has always worked

**Comment by ChShersh** [comment]
@arbus `hit clone` command was implemented by @vrom911 in #52. So now you should be able to just:

```haskell
hit clone holmusk/repo-name
```

This will clone repo with URL scheme consistent with the rest of the `hit`. I think we also can support parsing of SSH urls with optional `.git` suffix, but now at least with `hit clone` command you don't need to think about full URL.
