### ISSUE TITLE
`hit new` fails if the branch already exists

### ISSUE THREAD

**Issue by arbus** [kowainik/hit-on#58]
A good behaviour might be to catch this error, and just switch the command to a `hit hop` instead

![screenshot 2019-02-26 at 5 46 21 pm](https://user-images.githubusercontent.com/2200532/53403422-98cbbf00-39ee-11e9-992e-38529f6fffc6.png)

**Comment by vrom911** [comment]
I don't think that this is a reasonable default as it is not what one would expect from this command to do. 
Also, as we are not reusing internal of `git` but just run its commands, so it's not really possible to catch exactly this error and to handle it in a special way, so I'm not sure what `hit` should do here. It would be the same error if you would run this command through `git`.

If you think that it's a common use-case we can add another command which won't have misleading name `new` and will parse and analyse all local branches and checkout to one if it exists. On the other hand `git` works well with autocompletion for local branches.

**Comment by arbus** [comment]
fair enough, esp since catching this error will require more effort than it is worth.

I don't think it will be a common enough incident to warrant a new command so I'll close this for now
