### ISSUE TITLE
Implement `hit status` command with nice output

### ISSUE THREAD

**Issue by chshersh** [kowainik/hit-on#63]
See example of the output here:

* https://stackoverflow.com/a/55202319/2900502

**Comment by Jigar3** [comment]
Can I work on this issue ? @ChShersh 
Also, I tried 
```
ndiff = "!f() { TAB=`printf '\t'`; COLUMNS=`stty size|cut -d' ' -f2`; cd $GIT_PREFIX; git diff --name-status $1 | sort -k2 > /tmp/.tmpgitndiff ; git diff --stat=$COLUMNS,800 $1 |sed -e '$d' -e \"s/^ *//;s/ /${TAB}/\" | sort | join -t \"${TAB}\" -1 2 -2 1 -o 1.1,2.1,2.2 /tmp/.tmpgitndiff - | sed \"s/${TAB}/ /g\"; rm -f /tmp/.tmpgitndiff; }; f"
```
pasting this in the alias section of  ```~/.gitconfig``` but can't use the ```ndiff``` command. 

```bash
~/d/Basic-C-programs (master↑1|●7✚3) $ git ndiff origin/master..HEAD -- .
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>
```

**Comment by ChShersh** [comment]
@Jigar3 I appreciate your will to contribution to this project! However, not all design decisions are made for the issue yet, so it is too early to start working on it.

**Comment by Jigar3** [comment]
No issues. Let me know when all details are worked up, would like to work on this one. :smiley:
