### ISSUE TITLE
Implement `hit cur` command

### ISSUE THREAD

**Issue by ChShersh** [kowainik/hit-on#64]
Like `hit current` but shows only branch name.

**Comment by vrom911** [comment]
And probably it also show `git status`?

**Comment by ChShersh** [comment]
@vrom911 Yes, this would be nice! I often want to see current branch and all local changes. Maybe in that case `hit cur` command is redundant? We can just show this all information under `hit status` command?

**Comment by vrom911** [comment]
Yeah, that is a more obvious name.
