### ISSUE TITLE
Should we align issues?

### ISSUE THREAD

**Issue by chshersh** [kowainik/hit-on#76]
I noticed that issues are not aligned when there are different sizes of issue numbers. Aligning is more complicated, and it's not that important. I just wonder, whether we should align them or not 🙂
<img width="472" alt="Screenshot 2019-07-08 at 12 46 56 PM" src="https://user-images.githubusercontent.com/4276606/60783763-b23ffd00-a17e-11e9-9fc0-f86e0f364e81.png">

P.S. Extra space after arrow is because of my recent changes... I will work on that to prettyfy.
P.P.S. We do a lot of pretty-printing of tables with alignment here, I wish there was a library to do this easily...

**Comment by vrom911** [comment]
Hmm, interesting observation! Taking into consideration that the possibility of having issue numbers > than 9999 we can usually align by 4 digits (as an option). But we can discuss other options as well :slightly_smiling_face:

**Comment by kahlil29** [comment]
@chshersh  @vrom911 
Yes I think alignment should be done. Would make the list look much neater! 
And using Veronika's suggestion of pad to length 4 (with spaces), I think it can be implemented quite easily right? 

I would like to take up this issue, if we would be implementing this.

**Comment by kahlil29** [comment]
Okay I just realized that we are probably getting the entire entry as one `Text`, so it may not be as straightforward as I first imagined. 

I think it can still be done with some text/string processing. 
Or else we can consider using `Attoparsec` or some similar parser, but I feel that this may be a minor thing and using a parser combinator library may be overkill.

**Comment by vrom911** [comment]
@kahlil29 I think this piece of code can be taken look at:

https://github.com/kowainik/hit-on/blob/4e57daebf41d5aed425ddd05e39f5fd4ac77c995/src/Hit/Issue.hs#L54-L57

Here we are showing one issue with putting the colours and issue number into brackets. Depending on what we choose we should hardcode the alignment number to four or to count it each time on all iissue numbers and then decide.

**Comment by kahlil29** [comment]
@vrom911 Thanks for pointing to the exact function in the code. 
I think keeping a length of 4 is safe enough 😄

**Comment by chshersh** [comment]
There are a couple of helper functions for alignment:

https://github.com/kowainik/hit-on/blob/cda4a2e074f82e4f23cce0281e0dec03aeb61055/src/Hit/Git/Status.hs#L113-L117

I think, if somebody wants to take the issue, he/she can refactor them in a separate module and reuse.

I agree that aligning to 4 characters should be good enough. We only need to decide, how we want it to be:

like this:

```
[#12  ] Foo
[#1234] Bar
```

or like this

```
[#12]   Foo
[#1234] Bar
```

**Comment by vrom911** [comment]
Voting for the second option definitely! Also it won't be so noticeble when having only 1-digit numbers:

```
[#1]    One
[#2]    Two
```

instead of
```
[#1   ] One
[#2   ] Two
```

**Comment by chshersh** [comment]
> Also, it won't be so noticeable when having only 1-digit numbers:

Yeah, I was afraid about that. I guess in that case it's probably better to calculate max width of the issue number and add padding to the corresponding lines. This shouldn't be too hard, I already did something similar for `hit status` command. So we can implement this properly once and _forall_ and forget about this problem.

**Comment by kahlil29** [comment]
Yes I also am in favor of the 2nd option and I think what you suggested above is a good idea, calculating max length (width) of issue number and then passing it as an argument so that all padding uses it as a reference value. 

Can I work on this issue then?

**Comment by chshersh** [comment]
@kahlil29 Sure! Go ahead :slightly_smiling_face:
